apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogify-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogify-app
  template:
    metadata:
      labels:
        app: blogify-app
    spec:
      containers:
        - name: blogify-app
          image: mdzahid786/blogify:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://root:root@mongo:27017/blogify?authSource=admin&w=1
---
apiVersion: v1
kind: Service
metadata:
  name: blogify-app-service
spec:
  selector:
    app: blogify-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
